-- ============================================================================
-- V10: ad_promotion 表 —— 广告推广管理
-- ----------------------------------------------------------------------------
-- 字段说明：
--   id                  主键（IDENTITY，兼容 PostgreSQL 与 H2 MODE=PostgreSQL）
--   ad_union            广告联盟（如：淘宝联盟、京东联盟）
--   ad_union_symbol     联盟标识（如：pub.alimama.com）
--   ad_placement        推广位名称（如：首页顶部横幅广告）
--   pid                 推广位ID（如：mm_10463602253_3429100）
--   product_description 商品描述（广告展示文案）
--   product_url         商品图片URL（广告展示图片）
--   ad_url              广告链接（点击跳转URL）
--   ad_start            广告开始日期（生效时间）
--   ad_end              广告到期日期（失效时间）
--   ad_enabled          广告启用标志（true=有效，false=失效）
--   ad_location         广告投放位置描述（如：网站首页中部广告位）
--   ad_location_symbol  投放位置标识（如：home_middle）
--   created_at          创建时间
--   updated_at          更新时间
--
-- 索引：
--   idx_ad_promotion_location_symbol  (ad_location_symbol) 位置标识索引
--   idx_ad_promotion_enabled         (ad_enabled) 启用状态索引
-- ============================================================================

CREATE TABLE IF NOT EXISTS ad_promotion (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ad_union            VARCHAR(32)  NOT NULL,
    ad_union_symbol     VARCHAR(128) NOT NULL,
    ad_placement        VARCHAR(32)  NOT NULL,
    pid                 VARCHAR(64)  NOT NULL,
    product_description VARCHAR(128) NOT NULL,
    product_url         VARCHAR(256) NOT NULL,
    ad_url              VARCHAR(256) NOT NULL,
    ad_start            TIMESTAMP    NOT NULL,
    ad_end              TIMESTAMP    NOT NULL,
    ad_enabled          BOOLEAN      NOT NULL DEFAULT TRUE,
    ad_location         VARCHAR(32)  NOT NULL,
    ad_location_symbol  VARCHAR(32)  NOT NULL,
    created_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 位置标识索引：支持按投放位置查询
CREATE INDEX IF NOT EXISTS idx_ad_promotion_location_symbol ON ad_promotion (ad_location_symbol);

-- 启用状态索引：支持查询当前有效广告
CREATE INDEX IF NOT EXISTS idx_ad_promotion_enabled ON ad_promotion (ad_enabled);

-- ============================================================================
-- 初始数据：阿里云轻量云服务器广告（仅在不存在时插入）
-- ============================================================================

INSERT INTO ad_promotion 
    (ad_union, ad_union_symbol, ad_placement, pid, product_description, product_url, ad_url, ad_start, ad_end, ad_enabled, ad_location, ad_location_symbol)
SELECT 
    '淘宝联盟',
    'pub.alimama.com',
    '首页中部横幅广告',
    'mm_10463602253_3429100_1011630105018',
    '阿里云轻量云服务器｜建站、程序测试优选，到手68元起',
    'https://lf-cdn.trae.com/obj/trae-ai-image/page_image/763423105e883aa7f5bd984bf93a8fb.jpeg',
    'https://s.click.taobao.com/ThU6Q6k',
    '2026-07-25 00:00:00',
    '2027-05-18 23:59:59',
    TRUE,
    '网站首页中部广告位',
    'home_middle'
WHERE NOT EXISTS (
    SELECT 1 FROM ad_promotion WHERE ad_location_symbol = 'home_middle'
);
