-- 意见反馈留言表
-- 兼容 PostgreSQL 与 H2（MODE=PostgreSQL）：主键使用 IDENTITY，避免 SERIAL 等 PG 特有语法
-- （遵循 db/migration/README.md 的兼容性约定）
CREATE TABLE feedback_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content TEXT NOT NULL,
    nickname VARCHAR(30),
    contact VARCHAR(100),
    ip VARCHAR(45),
    status VARCHAR(20) NOT NULL DEFAULT 'visible',
    admin_reply TEXT,
    reply_at TIMESTAMP,
    reply_by VARCHAR(50),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_feedback_status_created ON feedback_messages(status, created_at);
CREATE INDEX idx_feedback_created_at ON feedback_messages(created_at);
