-- ============================================================================
-- V2: tool_event_logs 表 —— 原始事件日志
-- ----------------------------------------------------------------------------
-- 字段说明：
--   id         主键（IDENTITY）
--   tool_id    外键 → tools.id
--   anon_id    匿名用户 ID（客户端 localStorage 生成的 UUID）
--   event_type 事件类型：page_view / tool_use / copy / download
--   created_at 创建时间（JPA @CreatedDate 审计填充）
--
-- 索引：
--   idx_tool_event_logs_tool_created  (tool_id, created_at) 按工具查事件
--   idx_tool_event_logs_anon_created  (anon_id, created_at) 按用户查事件/防刷
-- ============================================================================

CREATE TABLE tool_event_logs (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tool_id    BIGINT       NOT NULL,
    anon_id    VARCHAR(64)  NOT NULL,
    event_type VARCHAR(30)  NOT NULL,
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_tool_event_logs_tool
        FOREIGN KEY (tool_id) REFERENCES tools (id)
);

-- (tool_id, created_at)：按工具查询事件历史
CREATE INDEX idx_tool_event_logs_tool_created ON tool_event_logs (tool_id, created_at);

-- (anon_id, created_at)：按匿名用户查询事件 / 频率限制防刷
CREATE INDEX idx_tool_event_logs_anon_created ON tool_event_logs (anon_id, created_at);
