-- ============================================================================
-- V4: tool_likes 表 —— 点赞记录
-- ----------------------------------------------------------------------------
-- 字段说明：
--   id         主键（IDENTITY）
--   tool_id    外键 → tools.id
--   anon_id    匿名用户 ID（客户端 localStorage 生成的 UUID）
--   created_at 创建时间（JPA @CreatedDate 审计填充）
--
-- 约束：
--   uk_tool_likes_tool_anon  (tool_id, anon_id) 唯一约束
--     防止同一匿名用户对同一工具重复点赞（一设备一次，不可取消）
-- ============================================================================

CREATE TABLE tool_likes (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tool_id    BIGINT       NOT NULL,
    anon_id    VARCHAR(64)  NOT NULL,
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_tool_likes_tool_anon
        UNIQUE (tool_id, anon_id),
    CONSTRAINT fk_tool_likes_tool
        FOREIGN KEY (tool_id) REFERENCES tools (id)
);
