-- ============================================================================
-- V5: site_visitor_daily 表 —— 站点日统计（PV/UV）
-- ----------------------------------------------------------------------------
-- 字段说明：
--   id          主键（IDENTITY）
--   stat_date   统计日期，唯一
--   pv          页面浏览量（Page View）
--   uv          独立访客数（Unique Visitor，按 anon_id 去重）
--   created_at  创建时间（JPA @CreatedDate 审计填充）
--   updated_at  更新时间（JPA @LastModifiedDate 审计填充）
--
-- 索引：
--   uk_site_visitor_daily_stat_date  stat_date 唯一索引
-- ============================================================================

CREATE TABLE site_visitor_daily (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stat_date  DATE      NOT NULL,
    pv         BIGINT    NOT NULL DEFAULT 0,
    uv         BIGINT    NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- stat_date 唯一索引：每天仅一条统计记录
CREATE UNIQUE INDEX uk_site_visitor_daily_stat_date ON site_visitor_daily (stat_date);
