-- ============================================================================
-- V6: 工具元数据种子数据 —— 10 个工具（7 个开发者工具 + 3 个图片工具）
-- ----------------------------------------------------------------------------
-- 种子数据通过 Flyway 迁移初始化，slug/名称/分类/关键词/描述参照 UI 设计稿。
-- use_count / like_count 设为合理的初始值，用于列表页热门排序与详情页计数展示。
-- enabled 全部为 true，created_at / updated_at 设为当前时间。
--
-- 注意：使用标准 INSERT 语句，兼容 H2（MODE=PostgreSQL）与 PostgreSQL。
--       id 由 GENERATED BY DEFAULT AS IDENTITY 自动分配，不显式指定。
-- ============================================================================

INSERT INTO tools (slug, name, category, keywords, description, enabled, use_count, like_count, created_at, updated_at)
VALUES
    -- ---- 开发者工具（7 个） ----
    ('json-formatter', 'JSON格式化', 'developer',
     'json,format,beautify,minify,validate',
     'JSON美化、压缩、语法校验，错误定位提示',
     TRUE, 0, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    ('url-encode', 'URL编码解码', 'developer',
     'url,encode,decode,uri,component',
     'URL Encode/Decode，一键复制',
     TRUE, 0, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    ('base64', 'Base64编码', 'developer',
     'base64,encode,decode,utf8',
     '文本Base64编解码，UTF-8支持',
     TRUE, 0, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    ('timestamp', '时间戳转换', 'developer',
     'timestamp,unix,date,time,转换',
     '秒/毫秒时间戳与日期互转',
     TRUE, 0, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    ('regex-tester', '正则测试', 'developer',
     'regex,regexp,正则,匹配,高亮',
     '正则匹配、高亮、分组信息展示',
     TRUE, 0, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    ('jwt-decoder', 'JWT解析', 'developer',
     'jwt,json,web,token,decode',
     'Header/Payload解析，过期时间提示',
     TRUE, 0, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    ('hash', '哈希计算', 'developer',
     'hash,md5,sha1,sha256,摘要',
     'MD5/SHA1/SHA256哈希计算',
     TRUE, 0, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    -- ---- 图片工具（3 个） ----
    ('image-compress', '图片压缩', 'image',
     'image,compress,压缩,jpg,png,webp',
     '本地压缩JPG/PNG/WEBP，不上传',
     TRUE, 0, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    ('image-crop', '图片裁剪', 'image',
     'image,crop,裁剪,resize,尺寸',
     '裁剪、旋转、自定义尺寸导出',
     TRUE, 0, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    ('image-convert', '格式转换', 'image',
     'image,convert,转换,png,jpg,webp',
     'PNG/JPG/WEBP互转，透明背景处理',
     TRUE, 0, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
